@startuml name Future 2.0 Context
title DataMart

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml





System_Boundary(f20, "Future20", ""){
    Person(uClient, "Сотрудник", "Сотрудник компании")
    System(f20MainOffice, "Головной офис", "") 
    System(f20Clinic, "Клиники", "")    
    System(sDWH, "Хранилище данных", "DataLakeHouse")
}

System_Ext(extAI, "ИИ-сервисы", "работы с мед. данными")
System_Ext(extFin, "Финтех-сервисы", "компании с банковской лицензией")


Rel(uClient, sDWH, "Отченость")

Rel(extAI, sDWH, "Мед. данные")
Rel(extFin, sDWH, "Фин. данные")
Rel(f20Clinic, sDWH, "Мед. данные")
Rel(f20MainOffice, sDWH, "Фин. данные")




@enduml

